### ISSUE TITLE
[Enhancement] Download animations

### ISSUE THREAD

**Issue by Mayurifag** [hidefromkgb/DPengine_old#2]
A little reminder to let user manually or automatically download the folder «Ponies» with animations from github or elsewhere.

**Comment by hidefromkgb** [comment]
Started adding; see ecb6103

**Comment by hidefromkgb** [comment]
Seems to be ready: https://github.com/hidefromkgb/DPengine/releases/tag/0.1a

**Comment by Mayurifag** [comment]
It works, thanks!
