### ISSUE TITLE
[macOS Sierra] DPEngine segfaults on exit

### ISSUE THREAD

**Issue by octylFractal** [hidefromkgb/DPengine_old#4]
When I close the pony chooser, DPEngine segfaults.

**Comment by hidefromkgb** [comment]
Yup, this is a [known issue](https://www.ponychan.net/fan/res/458.html#2457). Currently investigating.

**Comment by hidefromkgb** [comment]
Allegedly fixed by 966a45b, please test.

**Comment by octylFractal** [comment]
I think it's fixed, it doesn't seem to crash anymore.

**Comment by hidefromkgb** [comment]
Good.
Closing as fixed.
