### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by RoosterDragon** [hidefromkgb/DPengine_old#5]
I'd love to link this more, it'd be great if it had a ready-to-go release for those who aren't build-from-source types.

**Comment by hidefromkgb** [comment]
Will do!
I just need some time, till Sunday most probably, to add a network update feature suggested by @Mayurifag. When it\`s ready, the release package will only have to contain a sole executable file, without the animation base. That, BTW, will also spare me from keeping its duplicate in the source tree.

**Comment by hidefromkgb** [comment]
Done.
https://github.com/hidefromkgb/DPengine/releases

**Comment by RoosterDragon** [comment]
[Added this & other projects to the readme](https://github.com/RoosterDragon/Desktop-Ponies/commit/2076f306b5177e259e8b23f5a2e252c7e908a6be)
