### ISSUE TITLE
Can't compile Linux

### ISSUE THREAD

**Issue by octylFractal** [hidefromkgb/DPengine_old#6]
```
$ make
gcc `pkg-config gtk+-2.0 gtkglext-1.0 gtkglext-x11-1.0 --cflags` -I../core -Wall -ffunction-sections -fdata-sections -I/usr/include/gtkglext-1.0 -I/usr/lib/gtkglext-1.0/include -c lib.c -o .obj/lib.o
lib.c:260:18: error: unknown type name ‘THRD’
 void lMakeThread(THRD *thrd) {
                  ^~~~
Makefile:95: recipe for target '.obj/lib.o' failed
make: *** [.obj/lib.o] Error 1
```

It looks like you dropped some types that were used in Linux `lib.c` in https://github.com/hidefromkgb/DPengine/commit/84e258d1dd6d08641edfd0fc21646430f833be36#diff-8f37e6166aaaa224bab434fb588fbb75L38.

**Comment by hidefromkgb** [comment]
Yep. I\`ll soon update both Linux and Mac branches.

**Comment by hidefromkgb** [comment]
Does da792adc289032f10d11520faf3db96d2265a06d help?

**Comment by octylFractal** [comment]
Sorry for the long delay, but yea! I have more issues though, which I'll open separately.
