### ISSUE TITLE
Segfault on linux

### ISSUE THREAD

**Issue by octylFractal** [hidefromkgb/DPengine_old#8]
`master` current segfaults on Ubuntu 17.10. `gdb` tells me it happens right here: https://github.com/hidefromkgb/DPengine/blob/master/exec/exec.c#L1190

More gdb output can be found here: https://gist.github.com/kenzierocks/56706d0b6fa08de7cf2f5ba7be1b763b

**Comment by hidefromkgb** [comment]
25da335 should fix the segfault, please verify.

**Comment by octylFractal** [comment]
Looks good on my side. Thanks!
