### ISSUE TITLE
Documentation - add Linux build requirements

### ISSUE THREAD

**Issue by Liz4v** [hidefromkgb/DPengine_old#9]
I have a brand new Ubuntu 18.04 install and I had to install the following:

make
gcc
mesa-common-dev
libgtk2.0-dev
libgtkglext1-dev
libcurl4-openssl-dev
libssl-dev

Yes, of course the first few requirements were no surprise. :)

It's also surprising that I have to get into the linux folder and run the Makefile, and the result gets put outside. Some 'build' commands at root would be helpful probably.

(Also it segfaults right after downloading all ponies, and then instantly on running afterwards. I'll probably try to investigate why, when I find the time in a few weeks.)

**Comment by hidefromkgb** [comment]
Sorry for the late answer. I\`ve got sidetracked from DPE, since only three people, you being the third, ever got interested in it at all, to say nothing of its development.
I do have a major refactoring in mind to add speech and interactions The Way They Need To Be Added, and the segfault is due to me abandoning the project in the middle of it =(

**Comment by Liz4v** [comment]
Anything I can help with? I did work with C++ for a year some time ago,
even though it was an MFC project.

**Comment by hidefromkgb** [comment]
Maybe.
I\`ve got a task I\`m too scared of right now; it might so happen that you are the one who could help me with it.

At the beginning of DPE I was so obsessed with beating DP in terms of execution speed that I not only offloaded all output to the GPU via OpenGL, but I also coded my shaders to be as close to hardware as possible, which made them barely comprehensible.
Unfortunately, at that time both [the vertex shader](https://github.com/hidefromkgb/DPengine/blob/3e63c3586efc2e960fc97c44f118d3116e70bc5f/core/ogl/oglstd.c#L63) and [its pixel counterpart](https://github.com/hidefromkgb/DPengine/blob/3e63c3586efc2e960fc97c44f118d3116e70bc5f/core/ogl/oglstd.c#L126) were both separate files, so I could not comment them without wasting precious shader source size. Well, at least I did make them run fast — at the price of them becoming an unmaintainable mess…
As of now they are stored as strings which greatly simplifies adding comments, but the damage has already been done.

Before I add speech bubbles I need to reserve space for their pixel data in both the [main frame bank](https://github.com/hidefromkgb/DPengine/blob/3e63c3586efc2e960fc97c44f118d3116e70bc5f/core/ogl/oglstd.c#L101) (stored as a 3D texture) and the palette storage. It\`s nominally 3D as well, but currently has no way to provide any layers except the first, thus being a simple 2D texture — plus all the limitations of a 3D texture like quarter the layer size compared to 2D on most Intel cards.

Reserving new frames in the frame bank is easy, whereas reserving new palettes is not. The single-layeredness of the palette storage is buried deep inside my shaders, so it takes to rewrite them from the ground up to overcome it.

BTW, thanks to you I\`m going to try and continue developing. In particular, I already know why it segfaults; stay tuned =)

**Comment by hidefromkgb** [comment]
25da335 should fix the segfault, please verify.

**Comment by Liz4v** [comment]
The segfault is fixed-- mostly! Now it leads the pony selector, and I can pick ponies and watch them frolic. Only problem is when Pinkie rides the chopper it glitches often, and it has segfaulted once during that. But definitely the big impediment is gone!

I'll be honest that most of that explanation I only understand the theory, as I've never worked with shaders or textures directly. I'll see if I can find some tutorial. :thinking:
